[RFC] Support for objects (~relocatable)
WayfireWM/wf-config pull request #33
Opened 2020-10-30 14:31 UTC by myfreeweb

This is a prototype implementation of my idea for good support of configuring arbitrary instances of an object, like outputs and inputs in core, wallpapers in my upcoming wallpaper plugin, etc.

My explanations on IRC might have made it seem more complicated, but it really is simple, the idea is: we use sections for objects **like core already does for outputs** but we **add conventions/metadata** to make it possible for metadata consumers (wf-gsettings, wcm) to create automatic UI for these sections, and **implement section cloning** to make the metadata actually useful at runtime — i.e. **xml will be used for types/defaults/bounds on these dynamic sections** and stuff like `add_if_missing` that core does for outputs is no longer necessary!

## Example usage: outputs in core

example text config part:

```ini
[core.output:WL-1]
scale = 2.0
```

`metadata/core.output.xml`: (note: `object` element is equivalent to `plugin` but can be treated differently by consumers — and looks better than something like `<plugin name="xxx" relocatable="true">` IMO, but syntax can be bikeshedded endlessly :D)

```xml
<?xml version="1.0"?>
<wayfire>
	<object name="core.output">
		<_short>Output</_short>
		<_long>Display output settings.</_long>
		<category>General</category>
		<option name="mode" type="string">
			<_short>Mode</_short>
			<_long>Sets the resolution and refresh rate for the display.</_long>
			<default>default</default>
		</option>
		<option name="scale" type="double">
			<_short>Render scale</_short>
			<_long>Sets the rendering scale for the display. Can be fractional.</_long>
			<default>1.0</default>
			<min>1.0</min>
			<max>10.0</max>
		</option>
		<option name="layout" type="string">
			<_short>Layout</_short>
			<_long>Sets the position of the display.</_long>
			<default>default</default>
		</option>
		<option name="transform" type="string">
			<_short>Transform</_short>
			<_long>Sets the rotation for the display.</_long>
			<default>normal</default>
		</option>
	</object>
</wayfire>
```

Hopefully it's obvious how consumers like wcm could generate UI for this xml that would produce the config above. And in core, the result of parsing will be used as a template to be cloned into e.g. `core.output:WL-1` — so the types will be checked in the above config.

And here's the diff:

```diff
diff --git i/metadata/meson.build w/metadata/meson.build
index b34da6db..5a92a9c9 100644
--- i/metadata/meson.build
+++ w/metadata/meson.build
@@ -4,6 +4,7 @@ install_data('autostart.xml', install_dir: conf_data.get('PLUGIN_XML_DIR'))
 install_data('blur.xml', install_dir: conf_data.get('PLUGIN_XML_DIR'))
 install_data('command.xml', install_dir: conf_data.get('PLUGIN_XML_DIR'))
 install_data('core.xml', install_dir: conf_data.get('PLUGIN_XML_DIR'))
+install_data('core.output.xml', install_dir: conf_data.get('PLUGIN_XML_DIR'))
 install_data('cube.xml', install_dir: conf_data.get('PLUGIN_XML_DIR'))
 install_data('decoration.xml', install_dir: conf_data.get('PLUGIN_XML_DIR'))
 install_data('expo.xml', install_dir: conf_data.get('PLUGIN_XML_DIR'))
diff --git i/src/core/output-layout.cpp w/src/core/output-layout.cpp
index 6bb8cd48..3e67eca2 100644
--- i/src/core/output-layout.cpp
+++ w/src/core/output-layout.cpp
@@ -286,13 +286,17 @@ struct output_layout_output_t
     {
         std::string output_name = handle->name;
         auto& config = wf::get_core().config;
-        if (!config.get_section(output_name))
+        if (!config.get_section("core.output:" + output_name) && !config.get_section(output_name))
         {
             config.merge_section(
-                std::make_shared<wf::config::section_t>(output_name));
+                config.get_section("core.output")->clone_with_name("core.output:" + output_name));
         }
 
-        auto section = config.get_section(output_name);
+        auto section = config.get_section("core.output:" + output_name);
+        if (!section)
+            section = config.get_section(output_name);
+
+        // XXX: remove when removing support for legacy config (bare output_name)
         auto add_if_missing = [&] (std::string name, std::string defval)
         {
             if (!section->get_option_or(name))
```

With this example we can see that a type error in the config would be detected by the config parser:
```
EE 30-10-20 15:51:24.128 - [subprojects/wf-config/src/file.cpp:299] Error in file wayfire.ini:44, invalid option value!
```

instead of the output handling part of core:

```
EE 30-10-20 15:50:18.961 - [src/core/output-layout.cpp:500] Invalid scale for WL-1 in config: lol
```

so the `add_if_missing` stuff could be deleted after support for old-style compatibility is dropped.

2020-10-30 22:00 UTC, soreau commented
My suggestion for the specific case of output configuration, is to follow the convention we already have for core options, where it makes sense to group like options in separate files. For example, there is 'core.xml' and 'input.xml', what's wrong with simply naming this file 'output.xml' and simply name the object 'output'?

2020-10-31 12:13 UTC, myfreeweb commented
Nothing really wrong, I just think this is a nice convention… and it will avoid the `input` collision (input device vs global input options). Though maybe the input device should be `input.device`. But in that case `output.device` should be used for displays, but we don't have an `output` group with global output options. Argh.

Well, naming can be bikeshedded endlessly :) but this doesn't affect the code here, which just adds the *support* for using xml for dynamic `section_t`'s (and while core does use them for output and input devices, using them from plugins is a more urgent use case for me).

2020-10-31 12:18 UTC, ammen99 requested changes
A few general things:

- Use the same style for `{}` as in Wayfire (I should add CI here one day so that we can catch these errors more easily). So always `{}` and always on a new line.
- Add tests. I belive the test coverage for `wf-config` is nearly 100%, let's keep it that way.

2020-10-31 12:18 UTC, ammen99 commented on include/wayfire/config/option.hpp
> +        if constexpr (std::is_arithmetic<Type>::value) {
If clonse is really supposed to clone the option, then you should also copy the current value of the option.

2020-11-01 13:35 UTC, ammen99 approved these changes
Thanks! I'll probably make output sections work with this once I start working on the config-provider stuff.

2020-11-01 13:35 UTC, merged